### ISSUE TITLE
你好，我看到一篇关于解决睡眠问题的帖子

### ISSUE THREAD

**Issue by WilliamWeijian** [Jonny-china/R720-15IKBN-Hackintosh-Clover#1]
![Screenshot_2019-11-27-20-32-47-580_com coolapk market](https://user-images.githubusercontent.com/58217741/69724109-255e0600-1156-11ea-9798-ca0726767a49.jpg)
![f18897cbf86c1742d851461696ffa701](https://user-images.githubusercontent.com/58217741/69724168-47f01f00-1156-11ea-80a6-6449f742154d.png)
![9ebc5824639442cc0e3cee9f57f57521](https://user-images.githubusercontent.com/58217741/69724182-4fafc380-1156-11ea-945f-4cb2a3a02ae2.png)

**Comment by WilliamWeijian** [comment]
不知道能不能帮到老哥你，我用你的efi一路顺风安装了10.15,谢谢老哥你，希望老哥早日解决睡眠问题，就完美了

**Comment by lichongjia** [comment]
睡眠问题大多数都是由于0D/6D返回值造成的,把你的DSDT原文件提取出来,修改睡眠唤醒的方法名,然后在SSDT里面重写判断的方法就好了.

**Comment by WilliamWeijian** [comment]
哇，好激动，大佬竟然百忙中回我了，要是大佬可以给我丢几个操作的截图就好了，我还是个小白，拜托大佬了，，，



见风致 <notifications@github.com> 于 2019年12月2日周一 下午8:10写道：

**Comment by lichongjia** [comment]
首先我不是这个仓库的维护者,也并非大佬,我只是无意间看到这个讨论了,顺便答了一句.你可以把你DSDT文件提取出来发给我(lichongjia@vip.qq.com),然后我帮你看看.看了之后才能说怎么操作,因为睡眠问题分很多情况

**Comment by Jonny-china** [comment]
@WilliamWeijian 项目已更新，可以试试新版的
