### ISSUE TITLE
hevc 硬解加速没有开启

### ISSUE THREAD

**Issue by wxdhd121** [Jonny-china/R720-15IKBN-Hackintosh-Clover#19]
hd630是可以开启hevc硬解加速的应该，但我调整了好几次都没能成功开启，大佬有办法解决吗？

**Comment by Jonny-china** [comment]
目前已经支持
<img width="888" alt="image" src="https://user-images.githubusercontent.com/31563977/170864139-b9dbc6d4-c01c-46bc-bf36-6cf251354681.png">
