### ISSUE TITLE
睡眠问题是USB问题，需要USB定制

### ISSUE THREAD

**Issue by yulianjie** [Jonny-china/R720-15IKBN-Hackintosh-Clover#2]
参考黑果小兵的博客[Hackintool(原Intel FB-Patcher)使用教程及插入姿势](https://blog.daliansky.net/Intel-FB-Patcher-tutorial-and-insertion-pose.html)，我已经定制好，目前10.15.1没有问题，我也放在GitHub上了，希望你不要介意我直接拿你的clover（目前还不怎么会GitHub，不会提交文件）。https://github.com/jackyu0915/Hackintosh_Of_Lenovo_R720

**Comment by Jonny-china** [comment]
我也是通过小兵的教程定制USB的，但是我是USB网卡，我唤醒日志一直打印不出，可能是我USB网卡会自动唤醒电脑

**Comment by yulianjie** [comment]
我之前在10.14上USB网卡是可以睡眠的，到了10.15上不可以，后来我买了dw1560，最近又试了试USB定制，没想到就好了。看到你的clover中并没有usbport.kext这个文件，而是存在usbinjectALL.kext这个原始的驱动。

**Comment by Jonny-china** [comment]
我在oc上用的USB定制，且用补丁方案，没用驱动，我试试用驱动方式，感谢
