### ISSUE TITLE
关于睡眠问题

### ISSUE THREAD

**Issue by Mr-Weik** [Jonny-china/R720-15IKBN-Hackintosh-Clover#20]
大佬您好，不知道关于睡眠方面您这个EFI有做相关的处理吗

**Comment by DreamSaddle** [comment]
你好，睡眠的话只能是关了。
合上盖子的话我都是弄一个不让睡眠的软件，影响不大。

**Comment by sxvst** [comment]
大佬，我有一份efi完美睡眠，就是不支持小键盘，您这个支持小键盘，不支持睡眠，可以整合一下么

**Comment by Jonny-china** [comment]
> 大佬，我有一份efi完美睡眠，就是不支持小键盘，您这个支持小键盘，不支持睡眠，可以整合一下么

我这边睡眠和休眠都正常，使用最新的试试呢
