### ISSUE TITLE
已更换 BCM94352z(DW1560)，无法使用剪贴板接力和 AirDrop，以太网卡无法使用  Use BCM94352z(DW1560).  Cannot use AirDrop, Handoff and Ethernet

### ISSUE THREAD

**Issue by ghost** [Jonny-china/R720-15IKBN-Hackintosh-Clover#21]
十分感谢作者您的配置，安装后基本上没有遇到什么问题，美中不足的是 AirDrop 与 Handoff 接力无法使用。 （同一 Apple ID）
AirDrop 发送的时候找不到我的设备，手机和平板之间却可以正常发送，电脑也无法接收。
无法共享剪切板

向大家请教是哪里出现了问题，万分感谢！

**Comment by chenyjie** [comment]
据远景反馈，这是macOS12上部分brcm网卡存在的普遍问题。个人觉得是BrcmPatchRAM驱动尚不完善，得等驱动作者更新

**Comment by ghost** [comment]
> 据远景反馈，这是macOS12上部分brcm网卡存在的普遍问题。个人觉得是BrcmPatchRAM驱动尚不完善，得等驱动作者更新

十分感谢🙏您的及时解答，实在抱歉刚开始使用 GitHub 看得并不是很及时，我十分认同你所说的「驱动问题」，看来 Monterey 还是有待提高兼容啊！ 还有一个小问题想再次向你请教，请问我的这个以太网口也无法使用，在 Network 里面 那个 Ethernet 又一个红色的小点，以太网口应该是 Realtek Family Controller，还是说必须得外接 Type-c 扩展坞再插网线呢？

**Comment by ghost** [comment]
> 十分感谢作者您的配置，安装后基本上没有遇到什么问题，美中不足的是 AirDrop 与 Handoff 接力无法使用。 （同一 Apple ID） AirDrop 发送的时候找不到我的设备，手机和平板之间却可以正常发送，电脑也无法接收。 无法共享剪切板
> 
> 向大家请教是哪里出现了问题，万分感谢！

问题已解决，更换无线网卡 BCM94360CS2 以及转接卡之后，AirDrop 以及 Universal Control 都可以正常使用。
