### ISSUE TITLE
各位大神帮帮忙，我是用oc引导安装10.15.4出错了，拜托了

### ISSUE THREAD

**Issue by WilliamFWJ** [Jonny-china/R720-15IKBN-Hackintosh-Clover#4]
![WeChat Image_20200409234535](https://user-images.githubusercontent.com/35882207/78913905-477c7300-7abc-11ea-82e1-e4b0a57d7bfe.jpg)
各位大神好，我想请教一下怎么用oc引导装系统，我的步骤是烧盘----替换oc----重启进u盘就这样了，不知道是我哪里出错了，还请各位大神帮帮忙，拜托了，
qq联系也行 2421203720

**Comment by Jonny-china** [comment]
@sjhcjsd1c2d 
你替换的是我这个项目的OC吗

**Comment by WilliamFWJ** [comment]
是的，不知道这个问题应该怎么解决，我的qq是2421203720
麻烦到大佬你了
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Jonny-china** [comment]
@sjhcjsd1c2d 
可以参考[这个](https://blog.daliansky.net/macOS-Catalina-10.15.4-19E266-Release-version-with-Clover-5107-original-image-Double-EFI-Version-UEFI-and-MBR.html)，先安装完成，在替换OC
![image](https://user-images.githubusercontent.com/31563977/78958814-c5239b80-7b1b-11ea-8de2-c24765d3da2a.png)

**Comment by BianTan** [comment]
> @sjhcjsd1c2d
> 可以参考[这个](https://blog.daliansky.net/macOS-Catalina-10.15.4-19E266-Release-version-with-Clover-5107-original-image-Double-EFI-Version-UEFI-and-MBR.html)，先安装完成，在替换OC
> ![image](https://user-images.githubusercontent.com/31563977/78958814-c5239b80-7b1b-11ea-8de2-c24765d3da2a.png)

大佬我安装 10.15.14 成功用默认的 CLOVER 可以进入系统，替换项目的 OC 之后也像楼上一样显示那些咋办

**Comment by Contour-D** [comment]
直接用oc安装也行鸭

**Comment by Jonny-china** [comment]
@BianTan  @WilliamFWJ  项目已更新，可以试试新版
