### ISSUE TITLE
老哥，这有一些efi，希望可以帮到你

### ISSUE THREAD

**Issue by WilliamFWJ** [Jonny-china/R720-15IKBN-Hackintosh-Clover#5]
大佬晚上好，我这有一个群里的efi，睡眠OK的，是clover引导的，我自己试过，但是只能u盘引导。
![qrcode_1586969801226](https://user-images.githubusercontent.com/35882207/79365539-56ac6680-7f7d-11ea-89b4-261c0cba8621.jpg)
![IMG_20200416_005626](https://user-images.githubusercontent.com/35882207/79365571-6035ce80-7f7d-11ea-8293-4bf202e22722.jpg)
图片是QQ群和群文件的截图
里面还有一些群友的efi，希望帮到老哥你

**Comment by Jonny-china** [comment]
@sd1v13dw13wew 感谢
