### ISSUE TITLE
内置显示屏黑屏

### ISSUE THREAD

**Issue by Mi0Chan** [Jonny-china/R720-15IKBN-Hackintosh-Clover#6]
Hackintosh 10.15.4  19E287，使用Daliansky提供的镜像安装，内置显示屏黑屏。

**Comment by Jonny-china** [comment]
兄弟我是正常的

**Comment by onism68** [comment]
兄弟，你是1050 2g版的嘛

**Comment by Huiaei** [comment]
同样的情况，加载完黑屏。启动项加了-igfxvesa就能亮，不过核显内存只有7mb。黑屏加了edid也依旧加载完黑屏。
这个问题困扰了好久了，还以为大佬的配置太老有问题了，还自己编了个oc引导，最后发现黑屏后有ding一声（好像是oc哪个参数，开机完成会有声音提示），尝试盲输密码也进桌面了（我开机自启有个软件通知会响）。

**Comment by onism68** [comment]
> 同样的情况，加载完黑屏。启动项加了-igfxvesa就能亮，不过核显内存只有7mb。黑屏加了edid也依旧加载完黑屏。
> 这个问题困扰了好久了，还以为大佬的配置太老有问题了，还自己编了个oc引导，最后发现黑屏后有ding一声（好像是oc哪个参数，开机完成会有声音提示），尝试盲输密码也进桌面了（我开机自启有个软件通知会响）。

@Huiaei 我也是这个问题,加载完黑屏, 但其实是开机了,黑屏的时候按esc之类的键,会咚咚咚的响,但好像是显示器没有驱动起来,我之前也尝试了很多次,但都没法解决...

**Comment by Huiaei** [comment]
也不知道是不是bios的问题。我的就放在下面，看看是不是bios调错了还是bios的版本问题。
![information](https://user-images.githubusercontent.com/36834765/97705471-1f537080-1aef-11eb-8759-f2b99c985072.jpg)
![configuration](https://user-images.githubusercontent.com/36834765/97705472-1fec0700-1aef-11eb-91e4-88874c472b56.jpg)
![security](https://user-images.githubusercontent.com/36834765/97705478-224e6100-1aef-11eb-8ef1-0d6f531096a8.jpg)
![boot](https://user-images.githubusercontent.com/36834765/97705480-237f8e00-1aef-11eb-98ba-18a8559ce01b.jpg)

**Comment by onism68** [comment]
你也是1050  2g版本的嘛？我看他们4g版的1050,1050ti好像都没有这问题？

**Comment by Huiaei** [comment]
> 你也是1050 2g版本的嘛？我看他们4g版的1050,1050ti好像都没有这问题？

是，2G的，不过屏蔽了应该不是这个问题吧。

**Comment by Jonny-china** [comment]
已更新项目，可以试试新版
