### ISSUE TITLE
刚入坑OC

### ISSUE THREAD

**Issue by jxp98** [Jonny-china/R720-15IKBN-Hackintosh-Clover#8]
老哥的OC不能直接用吗？是还要配置些什么东西吗  我是装到机械盘的 同R720-i5-7300  镜像是10.15.4

出现这个
pci configuration begin

然后就重启了

**Comment by Jonny-china** [comment]
按理说是直接可以用的，我是从10.15直接升上去的，没有重新装过

**Comment by jxp98** [comment]
> 按理说是直接可以用的，我是从10.15直接升上去的，没有重新装过

好吧。谢谢大佬 问一下10.15.4触摸板手势支持的功能多吗

**Comment by Jonny-china** [comment]
> > 按理说是直接可以用的，我是从10.15直接升上去的，没有重新装过
> 
> 好吧。谢谢大佬 问一下10.15.4触摸板手势支持的功能多吗

![image](https://user-images.githubusercontent.com/31563977/86536103-913bf480-bf17-11ea-86d5-54cdd46a56a1.png)
都在这里了

**Comment by jxp98** [comment]
> > > 按理说是直接可以用的，我是从10.15直接升上去的，没有重新装过
> > 
> > 
> > 好吧。谢谢大佬 问一下10.15.4触摸板手势支持的功能多吗
> 
> ![image](https://user-images.githubusercontent.com/31563977/86536103-913bf480-bf17-11ea-86d5-54cdd46a56a1.png)
> 都在这里了

噢噢  好的 谢谢
